// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoyi9DxDaztloybuuuScmCPGm3P8OJvOI',
    appId: '1:994937515348:web:57a721c1954d49539e6cc1',
    messagingSenderId: '994937515348',
    projectId: 'zaad-37498',
    authDomain: 'zaad-37498.firebaseapp.com',
    storageBucket: 'zaad-37498.firebasestorage.app',
    measurementId: 'G-Q7JFX3QP14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEmGofq4sn77mGePUujjxiHZQaB0VsTVY',
    appId: '1:994937515348:android:909c2d897278538d9e6cc1',
    messagingSenderId: '994937515348',
    projectId: 'zaad-37498',
    storageBucket: 'zaad-37498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkHsEvxZ83OPmYTdzRYHudjVyBZDHRsww',
    appId: '1:994937515348:ios:a3d2767c25b9e1139e6cc1',
    messagingSenderId: '994937515348',
    projectId: 'zaad-37498',
    storageBucket: 'zaad-37498.firebasestorage.app',
    iosBundleId: 'com.example.zad',
  );
}
